document.writeln("	<div class=\'positionNav\'>");
document.writeln("		<div class=\'positionNav-box1\'></div>");
document.writeln("		<div class=\'positionNav-box2\'>");
document.writeln("			<div class=\'positionNav-delete\'></div>");
document.writeln("			<div class=\'box\'>");
document.writeln("				<img src=\'img/kf.jpg\' width=\'100\' alt=\'\'>");
document.writeln("				<a href=\'https://vip.sssmy.com/app/index.php?i=156&c=entry&do=chosekefu&m=cy163_customerservice\'>风水手机号</a>");
document.writeln("				<a href=\'https://vip.sssmy.com/app/index.php?i=156&c=entry&id=65&qudao=&goodsid=0&merch=0&do=groupchat&m=cy163_customerservice\'>课程资讯</a>");
document.writeln("			</div>");
document.writeln("");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("");




document.writeln("	<div class=\'footer\'>");
document.writeln("		<div class=\'slogan\'>");
document.writeln("			<ul class=\'content\'>");
document.writeln("				<li>");
document.writeln("					网上选号");
document.writeln("					<p>");
document.writeln("						<span><a href=\'#\'>资费套餐</a></span>");
document.writeln("						<span><a href=\'#\'>移动选号</a></span>");
document.writeln("						<span><a href=\'#\'>选号帮助</a></span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					免费订购");
document.writeln("					<p>");
document.writeln("						<span><a href=\'#\'>订购须知</a></span>");
document.writeln("						<span><a href=\'#\'>订购方式</a></span>");
document.writeln("						<span><a href=\'#\'>退订流程</a></span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					客服回访");
document.writeln("					<p>");
document.writeln("						<span><a href=\'#\'>确认号码</a></span>");
document.writeln("						<span><a href=\'#\'>协商送货方式</a></span>");
document.writeln("						<span><a href=\'#\'>确认送货时间</a></span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					上门办理");
document.writeln("					<p>");
document.writeln("						<span><a href=\'#\'>免费送货区域</a></span>");
document.writeln("						<span><a href=\'#\'>免费送货时间</a></span>");
document.writeln("						<span><a href=\'#\'>加急送货政策</a></span>");
document.writeln("						<span><a href=\'#\'>退款说明</a></span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					验货付款");
document.writeln("					<p>");
document.writeln("						<span><a href=\'#\'>验证号码信息</a></span>");
document.writeln("						<span><a href=\'#\'>支付方式</a></span>");
document.writeln("						<span><a href=\'#\'>交易条款</a></span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<!-- -------------------------------------------------- -->");
document.writeln("		<div class=\'help-box\'>");
document.writeln("		<div class=\'help clearfix\'>");
document.writeln("			<div class=\'help-post\'>");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<dl class='aboutMe'><dt>关于我们</dt>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<dl class='myBuy'>");
document.writeln("							<dt>购物指南</dt>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<dl class='myProtect'>");
document.writeln("							<dt>服务保障</dd>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<dl class='myCenter'>");
document.writeln("							<dt>客服中心</dt>");
document.writeln("							<dd><a href='consult.html?operator=0'>移动客服</a></dd>");
document.writeln("							<dd><a href='consult.html?operator=1'>联通客服</a></dd>");
document.writeln("							<dd><a href='consult.html?operator=2'>电信客服</a></dd>");
document.writeln("						</dl>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<!-- bottom:right -->");
document.writeln("			<div class=\'infor\'>");
document.writeln("				<div class=\'wechatQRcode\'>");
document.writeln("					<h5>微信服务号</h5>");
document.writeln("					<div><img src=\'img/rwm.jpg\' alt=\'\' style=\'width:110px;height:110px;\'></div>");
document.writeln("				</div>");
document.writeln("				<div class=\'service-infor\'>");
document.writeln("					<h5>咨询热线</h5>");
document.writeln("					<p class=\'p1\'>咨询热线：09:00~21:00</p>");
document.writeln("					<p class=\'p2\'>4008818765</p>");
document.writeln("					<p class=\'p3\'>退款，退换货，轻松搞定！</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<!--  黑色导航  -->");
document.writeln("		<div class=\'footer-black clearfix\'>");
/* document.writeln("			<ul class=\'content\'>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>新闻中心</a>");
document.writeln("					<a href=\'#\'>精彩短信</a>");
document.writeln("					<a href=\'#\'>移动客服</a>");
document.writeln("					<a href=\'#\'>电信客服</a>");
document.writeln("					<a href=\'#\'>友情链接</a>");
document.writeln("					<a href=\'#\'>购物流程</a>");
document.writeln("					<a href=\'#\'>业务合作</a>");
document.writeln("					<a href=\'#\'>联系我们</a>");
document.writeln("				</li>");
document.writeln("			</ul>"); */
document.writeln("		</div>");
document.writeln("		<div class=\'footer-hui clearfix\'>");
document.writeln("			<div>");
document.writeln("				<span>北京挑号网服务中心：北京市西城区裕中西里30号楼 京ICP备12046762号-1 Copyright 2006-2013 Tiaohao.com北京挑号网-北京飞翔思拓科技有限公司 旗下网站. 法律顾问: 张党伟律师 北京市常鸿律师事务所</span>");
document.writeln("				<img src=\'img/footer-1.gif\' alt=\'\'>");
document.writeln("				<img src=\'img/footer-2.gif\' alt=\'\'>");
document.writeln("				<img src=\'img/footer-3.jpg\' alt=\'\'>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		<!-- ----------------------------------------------- -->");
document.writeln("	</div>	");
document.writeln("		");
document.writeln("		");